env_variables:
  REACT_APP_FB_API_KEY: AIzaSyCtMJVlqCUfURlDHSyLNI04gCV41VXaQGc
  REACT_APP_FB_AUTH_DOMAIN: batus-925ac.firebaseapp.com
  REACT_APP_FB_PROJECT_ID: batus-925ac
  REACT_APP_FB_STORAGE_BUCKET: batus-925ac.appspot.com
  REACT_APP_FB_MSG_SENDER_ID: 211406468016
  REACT_APP_FB_APP_ID: 1:211406468016:web:2e0d715ec1e5b737681c75
  REACT_APP_FB_MEASUREMENT_ID: G-JQ4V75ZFGX
  REACT_APP_BAT_SERVER_HOST: https://batus-server-dev-1.uc.r.appspot.com
  NODE_ENV: production